version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: generator-web-server-app
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - /mnt/hdd/workspace/blender/prop/zip:/mnt/hdd/workspace/blender/prop/zip
      - /mnt/hdd/workspace/blender/prop/image:/mnt/hdd/workspace/blender/prop/image
      - /mnt/hdd/workspace/blender/GenerateView/generator/image:/mnt/hdd/workspace/blender/GenerateView/generator/image
      - /mnt/hdd/workspace/blender/user-image:/mnt/hdd/workspace/blender/user-image
      - /mnt/hdd/workspace/blender/prop/detail:/mnt/hdd/workspace/blender/prop/detail
      - /mnt/hdd/workspace/blender/excel/proplist:/mnt/hdd/workspace/blender/excel/proplist
      - /mnt/hdd/workspace/blender/excel/nodelist:/mnt/hdd/workspace/blender/excel/nodelist
      - /mnt/hdd/workspace/blender/excel/quicknodelist:/mnt/hdd/workspace/blender/excel/quicknodelist
      - /mnt/hdd/workspace/blender/quick-node:/mnt/hdd/workspace/blender/quick-node
    depends_on:
      - db
      - redis
    networks:
      - app-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:8.0.32
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "13307:3306"
    env_file:
      - .env
    volumes:
      - /home/greneta/temp/MYSQL:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis_server
    hostname: redis_server
    restart: always
    ports:
      - "16379:6379"
    networks:
      - app-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    restart: always
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"

networks:
  app-network:
